#Import the Data

In [ ]:
!unzip movies_metadata.csv.zip -d .


Archive:  movies_metadata.csv.zip
  inflating: ./movies_metadata.csv   


In [ ]:
!unzip ratings.csv.zip

Archive:  ratings.csv.zip
  inflating: ratings.csv             


In [ ]:
import pandas as pd

movies_metadata = pd.read_csv('movies_metadata.csv', usecols=['id', 'original_title', 'popularity', 'genres', 'spoken_languages', 'vote_average'])
ratings = pd.read_csv('ratings.csv')

<ipython-input-3-b727d2d07026>:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_metadata = pd.read_csv('movies_metadata.csv', usecols=['id', 'original_title', 'popularity', 'genres', 'spoken_languages', 'vote_average'])


In [ ]:
movies_metadata.shape, ratings.shape

((45466, 6), (26024289, 4))

In [ ]:
movies_metadata.columns

Index(['genres', 'id', 'original_title', 'popularity', 'spoken_languages',
       'vote_average'],
      dtype='object')

In [ ]:
ratings.head(5)

userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [ ]:
movies_metadata

genres      id  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...     862   
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...    8844   
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   15602   
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   31357   
4                         [{'id': 35, 'name': 'Comedy'}]   11862   
...                                                  ...     ...   
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...  439050   
45462                      [{'id': 18, 'name': 'Drama'}]  111109   
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...   67758   
45464                                                 []  227506   
45465                                                 []  461257   

                    original_title popularity  \
0                        Toy Story  21.946943   
1                          Jumanji  17.015539   
2                 Grumpier Old Men    11.7129   
3                Waiting to Exhale   3.859495   
4      Father of the Bride Part II   8.387519   
...                            ...        ...   
45461                      رگ خواب   0.072051   
45462          Siglo ng Pagluluwal   0.178241   
45463                     Betrayal   0.903007   
45464          Satana likuyushchiy   0.003503   
45465                     Queerama   0.163015   

                                        spoken_languages  vote_average  
0               [{'iso_639_1': 'en', 'name': 'English'}]           7.7  
1      [{'iso_639_1': 'en', 'name': 'English'}, {'iso...           6.9  
2               [{'iso_639_1': 'en', 'name': 'English'}]           6.5  
3               [{'iso_639_1': 'en', 'name': 'English'}]           6.1  
4               [{'iso_639_1': 'en', 'name': 'English'}]           5.7  
...                                                  ...           ...  
45461             [{'iso_639_1': 'fa', 'name': 'فارسی'}]           4.0  
45462                  [{'iso_639_1': 'tl', 'name': ''}]           9.0  
45463           [{'iso_639_1': 'en', 'name': 'English'}]           3.8  
45464                                                 []           0.0  
45465           [{'iso_639_1': 'en', 'name': 'English'}]           0.0  

[45466 rows x 6 columns]

#Pre processing the data

Drop rows with no genres
-> If len(genres[i]) == 0, drop row

Drop rows where spoken languages is not English
-> If spoken_languages[0].name != 'English', drop row

Drop movies where popularity is less than 5
-> If popularity [i] <= 5: drop row

##Processing the movies dataframe


In [ ]:
# Convert the string representation of lists to actual lists
movies_metadata['spoken_languages'] = movies_metadata['spoken_languages'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Filter based on 'en' in the 'spoken_languages'
movies_metadata_filtered_genres_lang = movies_metadata[movies_metadata['spoken_languages'].apply(lambda x: any(lang['iso_639_1'] == 'en' for lang in x))]

# Drop rows with NaN in 'spoken_languages' (if needed)
movies_metadata_filtered_genres_lang.dropna(subset=['spoken_languages'], inplace=True)

<ipython-input-33-86520278a2a8>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_metadata_filtered_genres_lang.dropna(subset=['spoken_languages'], inplace=True)


In [ ]:
import ast

movies_metadata_filtered_genres = movies_metadata[movies_metadata['genres'] != '[]']
print("movies_metadata_filtered_genres : ", movies_metadata_filtered_genres.shape)

# Convert the string representation of lists to actual lists
movies_metadata_filtered_genres['spoken_languages'] = movies_metadata_filtered_genres['spoken_languages'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Filter based on 'en' in the 'spoken_languages'
movies_metadata_filtered_genres_lang = movies_metadata_filtered_genres[movies_metadata_filtered_genres['spoken_languages'].apply(lambda x: any(lang['iso_639_1'] == 'en' for lang in x))]

# Drop rows with NaN in 'spoken_languages' (if needed)
movies_metadata_filtered_genres_lang.dropna(subset=['spoken_languages'], inplace=True)

print(movies_metadata_filtered_genres_lang.shape)

movies_metadata_filtered_genres :  (43024, 6)
(28231, 6)


<ipython-input-42-a8830e8f5209>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_metadata_filtered_genres['spoken_languages'] = movies_metadata_filtered_genres['spoken_languages'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
<ipython-input-42-a8830e8f5209>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_metadata_filtered_genres_lang.dropna(subset=['spoken_languages'], inplace=True)


In [ ]:
movies_df = movies_metadata_filtered_genres_lang[['id', 'original_title', 'genres']]

In [ ]:
movies_df.reset_index(inplace=True, drop=True)
movies_df

id               original_title  \
0         862                    Toy Story   
1        8844                      Jumanji   
2       15602             Grumpier Old Men   
3       31357            Waiting to Exhale   
4       11862  Father of the Bride Part II   
...       ...                          ...   
28226  390959    Shadow of the Blair Witch   
28227  289923          The Burkittsville 7   
28228  222848              Caged Heat 3000   
28229   30840                   Robin Hood   
28230   67758                     Betrayal   

                                                  genres  
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...  
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...  
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...  
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  
4                         [{'id': 35, 'name': 'Comedy'}]  
...                                                  ...  
28226  [{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...  
28227                     [{'id': 27, 'name': 'Horror'}]  
28228           [{'id': 878, 'name': 'Science Fiction'}]  
28229  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...  
28230  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...  

[28231 rows x 3 columns]

In [ ]:
final_genres_list = []

for i in range(movies_df.shape[0]):
  genres = movies_df.iloc[i][2]
  genres_list = ast.literal_eval(genres)
  buffer_list = []
  for i in range(len(genres_list)):
    buffer_list.append(genres_list[i]['name'])
  final_genres_list.append(buffer_list)

In [ ]:
movies_df['genres'] = pd.Series(final_genres_list)

<ipython-input-65-dea258876960>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres'] = pd.Series(final_genres_list)


In [ ]:
movies_df

id               original_title                        genres
0         862                    Toy Story   [Animation, Comedy, Family]
1        8844                      Jumanji  [Adventure, Fantasy, Family]
2       15602             Grumpier Old Men             [Romance, Comedy]
3       31357            Waiting to Exhale      [Comedy, Drama, Romance]
4       11862  Father of the Bride Part II                      [Comedy]
...       ...                          ...                           ...
28226  390959    Shadow of the Blair Witch             [Mystery, Horror]
28227  289923          The Burkittsville 7                      [Horror]
28228  222848              Caged Heat 3000             [Science Fiction]
28229   30840                   Robin Hood      [Drama, Action, Romance]
28230   67758                     Betrayal     [Action, Drama, Thriller]

[28231 rows x 3 columns]

In [ ]:
df = pd.DataFrame(movies_df)

# Create a new DataFrame with one-hot encoding for genres
movies_matrix = pd.get_dummies(df['genres'].apply(pd.Series).stack()).sum(level=0)

# Combine with the movie IDs and titles
movies_matrix = pd.concat([df[['id', 'original_title']], movies_matrix], axis=1)

# Set 'id' as the index
movies_matrix.set_index('id', inplace=True)
movies_matrix.shape

<ipython-input-79-3632e744a984>:4: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  movies_matrix = pd.get_dummies(df['genres'].apply(pd.Series).stack()).sum(level=0)


(28231, 21)

In [ ]:
movies_matrix.head()

original_title  Action  Adventure  Animation  Comedy  \
id                                                                         
862                      Toy Story       0          0          1       1   
8844                       Jumanji       0          1          0       0   
15602             Grumpier Old Men       0          0          0       1   
31357            Waiting to Exhale       0          0          0       1   
11862  Father of the Bride Part II       0          0          0       1   

       Crime  Documentary  Drama  Family  Fantasy  ...  History  Horror  \
id                                                 ...                    
862        0            0      0       1        0  ...        0       0   
8844       0            0      0       1        1  ...        0       0   
15602      0            0      0       0        0  ...        0       0   
31357      0            0      1       0        0  ...        0       0   
11862      0            0      0       0        0  ...        0       0   

       Music  Mystery  Romance  Science Fiction  TV Movie  Thriller  War  \
id                                                                         
862        0        0        0                0         0         0    0   
8844       0        0        0                0         0         0    0   
15602      0        0        1                0         0         0    0   
31357      0        0        1                0         0         0    0   
11862      0        0        0                0         0         0    0   

       Western  
id              
862          0  
8844         0  
15602        0  
31357        0  
11862        0  

[5 rows x 21 columns]

In [ ]:
movies_list = list(movies_matrix.index)

##Processing the user ratings dataframe



Transformations:

Filter movie ID by the movies present in movie matrix

Create a user movie interaction matrix

In [ ]:
ratings = ratings[:50000]

In [ ]:
ratings = ratings[['userId', 'movieId', 'rating']]

In [ ]:
ratings

userId  movieId  rating
0           1      110     1.0
1           1      147     4.5
2           1      858     5.0
3           1     1221     5.0
4           1     1246     5.0
...       ...      ...     ...
49995     527    85131     1.0
49996     528      112     2.5
49997     528      163     2.0
49998     528      494     3.0
49999     528      553     3.5

[50000 rows x 3 columns]

In [ ]:
movies_list = [int(i) for i in movies_list]
len(movies_list)

28231

Careful, this cell takes a lot of time to execute as the time complexity of this function is insane.

In [ ]:
ratings_movies = ratings[ratings['movieId'].isin(movies_list)]

In [ ]:
ratings_movies

userId  movieId  rating
1           1      147     4.5
2           1      858     5.0
4           1     1246     5.0
5           1     1968     4.0
6           1     2762     4.5
...       ...      ...     ...
49977     527    44191     4.0
49979     527    46578     3.5
49997     528      163     2.0
49998     528      494     3.0
49999     528      553     3.5

[16774 rows x 3 columns]

In [ ]:
import pandas as pd

ratings_df = pd.DataFrame(ratings_movies)

# Create the user-movie matrix using pivot_table
user_movie_matrix = ratings_df.pivot_table(index='userId', columns='movieId', values='rating')

# Fill NaN values (movies not rated by users) with 0
user_movie_matrix = user_movie_matrix.fillna(0)


In [ ]:
user_movie_matrix.shape

(510, 1502)

#Final  screening of movie feature matrix and user-movie matrix

In [ ]:
dummy_movies_matrix = movies_matrix.reset_index()
dummy_movies_matrix.head()

id               original_title  Action  Adventure  Animation  Comedy  \
0    862                    Toy Story       0          0          1       1   
1   8844                      Jumanji       0          1          0       0   
2  15602             Grumpier Old Men       0          0          0       1   
3  31357            Waiting to Exhale       0          0          0       1   
4  11862  Father of the Bride Part II       0          0          0       1   

   Crime  Documentary  Drama  Family  ...  History  Horror  Music  Mystery  \
0      0            0      0       1  ...        0       0      0        0   
1      0            0      0       1  ...        0       0      0        0   
2      0            0      0       0  ...        0       0      0        0   
3      0            0      1       0  ...        0       0      0        0   
4      0            0      0       0  ...        0       0      0        0   

   Romance  Science Fiction  TV Movie  Thriller  War  Western  
0        0                0         0         0    0        0  
1        0                0         0         0    0        0  
2        1                0         0         0    0        0  
3        1                0         0         0    0        0  
4        0                0         0         0    0        0  

[5 rows x 22 columns]

In [ ]:
len(movies_in_user_movie_matrix)

1502

In [ ]:
movies_in_user_movie_matrix = list(user_movie_matrix.columns)
dummy_movies_matrix['id'] = pd.to_numeric(dummy_movies_matrix["id"])

In [ ]:
movies_matrix_filtered = dummy_movies_matrix[dummy_movies_matrix['id'].isin(movies_in_user_movie_matrix)]

In [ ]:
movies_matrix_filtered

id                        original_title  Action  Adventure  \
5       949                                  Heat       1          0   
14     1408                      Cutthroat Island       1          1   
15      524                                Casino       0          0   
17        5                            Four Rooms       0          0   
21     1710                               Copycat       0          0   
...     ...                                   ...     ...        ...   
27857  2791  The Chronicles of Riddick: Dark Fury       1          0   
27859  2154             The Dark Side of The Moon       1          0   
28037  3178                                  Beat       0          0   
28046  2331                                 Jesus       0          0   
28182  3104            Frankenstein Created Woman       0          0   

       Animation  Comedy  Crime  Documentary  Drama  Family  ...  History  \
5              0       0      1            0      1       0  ...        0   
14             0       0      0            0      0       0  ...        0   
15             0       0      1            0      1       0  ...        0   
17             0       1      1            0      0       0  ...        0   
21             0       0      0            0      1       0  ...        0   
...          ...     ...    ...          ...    ...     ...  ...      ...   
27857          1       0      0            0      0       0  ...        0   
27859          0       0      0            0      0       0  ...        0   
28037          0       0      0            0      1       0  ...        0   
28046          0       0      0            0      1       0  ...        1   
28182          0       0      0            0      0       0  ...        0   

       Horror  Music  Mystery  Romance  Science Fiction  TV Movie  Thriller  \
5           0      0        0        0                0         0         1   
14          0      0        0        0                0         0         0   
15          0      0        0        0                0         0         0   
17          0      0        0        0                0         0         0   
21          0      0        0        0                0         0         1   
...       ...    ...      ...      ...              ...       ...       ...   
27857       0      0        0        0                1         0         1   
27859       1      0        0        0                1         0         1   
28037       0      0        0        0                0         0         0   
28046       0      0        0        0                0         0         0   
28182       1      0        0        0                1         0         0   

       War  Western  
5        0        0  
14       0        0  
15       0        0  
17       0        0  
21       0        0  
...    ...      ...  
27857    0        0  
27859    0        0  
28037    0        0  
28046    0        0  
28182    0        0  

[1503 rows x 22 columns]

In [ ]:
movies_matrix_filtered = movies_matrix_filtered.drop_duplicates(subset=['id'], keep='first')
movies_matrix_filtered

id                        original_title  Action  Adventure  \
5       949                                  Heat       1          0   
14     1408                      Cutthroat Island       1          1   
15      524                                Casino       0          0   
17        5                            Four Rooms       0          0   
21     1710                               Copycat       0          0   
...     ...                                   ...     ...        ...   
27857  2791  The Chronicles of Riddick: Dark Fury       1          0   
27859  2154             The Dark Side of The Moon       1          0   
28037  3178                                  Beat       0          0   
28046  2331                                 Jesus       0          0   
28182  3104            Frankenstein Created Woman       0          0   

       Animation  Comedy  Crime  Documentary  Drama  Family  ...  History  \
5              0       0      1            0      1       0  ...        0   
14             0       0      0            0      0       0  ...        0   
15             0       0      1            0      1       0  ...        0   
17             0       1      1            0      0       0  ...        0   
21             0       0      0            0      1       0  ...        0   
...          ...     ...    ...          ...    ...     ...  ...      ...   
27857          1       0      0            0      0       0  ...        0   
27859          0       0      0            0      0       0  ...        0   
28037          0       0      0            0      1       0  ...        0   
28046          0       0      0            0      1       0  ...        1   
28182          0       0      0            0      0       0  ...        0   

       Horror  Music  Mystery  Romance  Science Fiction  TV Movie  Thriller  \
5           0      0        0        0                0         0         1   
14          0      0        0        0                0         0         0   
15          0      0        0        0                0         0         0   
17          0      0        0        0                0         0         0   
21          0      0        0        0                0         0         1   
...       ...    ...      ...      ...              ...       ...       ...   
27857       0      0        0        0                1         0         1   
27859       1      0        0        0                1         0         1   
28037       0      0        0        0                0         0         0   
28046       0      0        0        0                0         0         0   
28182       1      0        0        0                1         0         0   

       War  Western  
5        0        0  
14       0        0  
15       0        0  
17       0        0  
21       0        0  
...    ...      ...  
27857    0        0  
27859    0        0  
28037    0        0  
28046    0        0  
28182    0        0  

[1502 rows x 22 columns]

In [ ]:
movies = list(movies_matrix_filtered['original_title'])
movies_ids = movies_matrix_filtered['id']
final_movies_matrix = movies_matrix_filtered.reset_index(drop=True)
final_movies_matrix = final_movies_matrix.drop(['original_title', 'id'], axis = 1)

In [ ]:
final_movies_matrix

Action  Adventure  Animation  Comedy  Crime  Documentary  Drama  Family  \
0          1          0          0       0      1            0      1       0   
1          1          1          0       0      0            0      0       0   
2          0          0          0       0      1            0      1       0   
3          0          0          0       1      1            0      0       0   
4          0          0          0       0      0            0      1       0   
...      ...        ...        ...     ...    ...          ...    ...     ...   
1497       1          0          1       0      0            0      0       0   
1498       1          0          0       0      0            0      0       0   
1499       0          0          0       0      0            0      1       0   
1500       0          0          0       0      0            0      1       0   
1501       0          0          0       0      0            0      0       0   

      Fantasy  Foreign  History  Horror  Music  Mystery  Romance  \
0           0        0        0       0      0        0        0   
1           0        0        0       0      0        0        0   
2           0        0        0       0      0        0        0   
3           0        0        0       0      0        0        0   
4           0        0        0       0      0        0        0   
...       ...      ...      ...     ...    ...      ...      ...   
1497        0        0        0       0      0        0        0   
1498        0        0        0       1      0        0        0   
1499        0        0        0       0      0        0        0   
1500        0        0        1       0      0        0        0   
1501        0        0        0       1      0        0        0   

      Science Fiction  TV Movie  Thriller  War  Western  
0                   0         0         1    0        0  
1                   0         0         0    0        0  
2                   0         0         0    0        0  
3                   0         0         0    0        0  
4                   0         0         1    0        0  
...               ...       ...       ...  ...      ...  
1497                1         0         1    0        0  
1498                1         0         1    0        0  
1499                0         0         0    0        0  
1500                0         0         0    0        0  
1501                1         0         0    0        0  

[1502 rows x 20 columns]

In [ ]:
user_movie_matrix.head()
user_movie_columns = user_movie_matrix.columns
user_ids = user_movie_matrix.index
final_user_movie_matrix = user_movie_matrix.reset_index(drop=True)

In [ ]:
final_movies_matrix_np = final_movies_matrix.to_numpy()
final_user_movie_matrix_np = final_user_movie_matrix.to_numpy()

In [ ]:
final_movies_matrix_np.shape, final_user_movie_matrix_np.shape

((1502, 20), (510, 1502))

#Create Recommendation Algorithm
#Content Based

In [ ]:
import numpy as np
import tensorflow as tf

# tf.reset_default_graph()
print(tf.__version__)

2.13.0


In [ ]:
users = user_ids
movies = movies
features = user_movie_columns

num_users = len(users)
num_movies = len(movies)
num_feats = len(features)


In [ ]:
user_movies = final_user_movie_matrix_np

movies_feats = final_movies_matrix_np

In [ ]:
users_movies = tf.constant(user_movies, dtype = tf.float32)
movies_feats = tf.constant(movies_feats, dtype = tf.float32)

In [ ]:
wgtd_feature_matrices=[tf.expand_dims(tf.transpose(users_movies)[:,i],axis=1)*movies_feats for i in range(num_users)]

users_movies_feats = tf.stack(wgtd_feature_matrices)

In [ ]:
users_movies_feats

<tf.Tensor: shape=(510, 1502, 20), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [3., 3., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0

In [ ]:
users_movies_feats_sums = tf.reduce_sum(users_movies_feats, axis = 1)
users_movies_feats_totals = tf.reduce_sum(users_movies_feats_sums, axis = 1)

In [ ]:
users_movies_feats

<tf.Tensor: shape=(510, 1502, 20), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [3., 3., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0

In [ ]:
users_movies_feats_sums

<tf.Tensor: shape=(510, 20), dtype=float32, numpy=
array([[ 4.5,  4. ,  0. , ...,  0. ,  0. ,  0. ],
       [17. , 17. ,  0. , ...,  6. ,  0. ,  0. ],
       [ 2. ,  0. ,  0. , ...,  8. ,  0. ,  0. ],
       ...,
       [ 5. ,  5. ,  0. , ...,  9. ,  0. ,  3. ],
       [39. , 28. ,  0.5, ..., 38.5,  2.5,  5. ],
       [ 3. ,  5. ,  0. , ...,  0. ,  0. ,  2. ]], dtype=float32)>

In [ ]:
users_movies_feats_totals

In [ ]:
user_feat = [users_movies_feats_sums[i, :]/ users_movies_feats_totals[i]for i in range(num_users)]

In [ ]:
user_feat

In [ ]:
users_rating = [tf.map_fn(lambda x: tf.tensordot(user_feat[i], x, axes = 1), movies_feats) for i in range(num_users)]

all_users_ratings = tf.stack(users_rating)

Takes a very long time to compute (20 mins +) so upload all users ratings df and load using commented code.

In [ ]:
all_users_ratings_df = pd.DataFrame(all_users_ratings)
all_users_ratings_df.to_csv('all_users_ratings_df.csv', index = False)
# dummy = pd.read_csv('all_users_ratings_df.csv')
# dummy_np = dummy.to_numpy()
# dummy_np = tf.constant(dummy_np, dtype= tf.float32)

In [ ]:
all_users_ratings

<tf.Tensor: shape=(510, 1502), dtype=float32, numpy=
array([[0.39873415, 0.10759494, 0.34177214, ..., 0.17088607, 0.17088607,
        0.2278481 ],
       [0.6770833 , 0.35416666, 0.4375    , ..., 0.23958333, 0.23958333,
        0.03125   ],
       [0.54838705, 0.03225806, 0.38709676, ..., 0.20967741, 0.20967741,
        0.12903225],
       ...,
       [0.5132743 , 0.17699115, 0.26548672, ..., 0.20353982, 0.20353982,
        0.07079646],
       [0.505144  , 0.13786007, 0.34567901, ..., 0.2355967 , 0.2489712 ,
        0.07304527],
       [0.4137931 , 0.27586207, 0.31034482, ..., 0.18965517, 0.31034482,
        0.10344828]], dtype=float32)>

In [ ]:
all_users_ratings_new = tf.where(tf.equal(users_movies, tf.zeros_like(users_movies)),
                                 all_users_ratings,
                                 -np.inf*tf.ones_like(tf.cast(users_movies, tf.float32)))

In [ ]:
tf.equal(users_movies, tf.zeros_like(users_movies))

<tf.Tensor: shape=(510, 1502), dtype=bool, numpy=
array([[ True,  True,  True, ...,  True,  True,  True],
       [ True, False,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])>

In [ ]:
all_users_ratings_new

<tf.Tensor: shape=(510, 1502), dtype=float32, numpy=
array([[0.39873415, 0.10759494, 0.34177214, ..., 0.17088607, 0.17088607,
        0.2278481 ],
       [0.6770833 ,       -inf, 0.4375    , ..., 0.23958333, 0.23958333,
        0.03125   ],
       [0.54838705, 0.03225806, 0.38709676, ..., 0.20967741, 0.20967741,
        0.12903225],
       ...,
       [0.5132743 , 0.17699115, 0.26548672, ..., 0.20353982, 0.20353982,
        0.07079646],
       [0.505144  , 0.13786007, 0.34567901, ..., 0.2355967 , 0.2489712 ,
        0.07304527],
       [0.4137931 , 0.27586207, 0.31034482, ..., 0.18965517, 0.31034482,
        0.10344828]], dtype=float32)>

In [ ]:
users_movies

<tf.Tensor: shape=(510, 1502), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 3., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [ ]:
def find_user_top_movies(user_index, num_to_recommend):
  movies_ind = tf.nn.top_k(all_users_ratings_new[user_index], num_to_recommend)[1]
  return tf.gather_nd(movies, tf.expand_dims(movies_ind, axis = 1))

In [ ]:
user_topmovies = {}
num_to_recommend = tf.reduce_sum(tf.cast(tf.equal(users_movies, tf.zeros_like(users_movies)), dtype = tf.float32), axis = 1)
for ind in range(num_users):
  top_movies = find_user_top_movies(ind, tf.cast(num_to_recommend[ind], dtype = tf.int32))
  user_topmovies[users[ind]] = list(top_movies)

#Test the Recommendations

In [ ]:
first_user = final_user_movie_matrix_np[0]

movies_likes = []
buffer_movies = []

for i in range(0,len(first_user)):
  if first_user[i] != 0:
    movies_likes.append((i,first_user[i], movies[i]))
    buffer_movies.append(movies[i])

In [ ]:
len(movies_likes)

8

In [ ]:
buffer_movies

['Poetic Justice',
 'The Ghost of Frankenstein',
 'Ghost Dog: The Way of the Samurai',
 'The Ladykillers',
 'Catwoman',
 'Dr. Jekyll and Mr. Hyde',
 'Harry Potter and the Goblet of Fire',
 "Don't Lose Your Head"]

In [ ]:
recommendations = user_topmovies[1]

In [ ]:
recommendations[:5]

[<tf.Tensor: shape=(), dtype=string, numpy=b'My Super Ex-Girlfriend'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'The Ice Harvest'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Zaat'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Blue Thunder'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Westworld'>]